### ISSUE TITLE
Mysql2::Error: Table 'blog.Relationships' doesn't exist

### ISSUE THREAD

**Issue by MyHPPY** [adeyahya/rails-blog#2]
Terimakasih sudah berbagi ilmu[SOLVED]

Saya sudah download dan dijalankan. Namun ketika saya buat user baru berhasil namun muncul error seperti berikut
```
Mysql2::Error: Table 'blog.Relationships' doesn't exist: SELECT  `articles`.* FROM `articles` WHERE (user_id IN (SELECT followed_id FROM Relationships WHERE follower_id = 1) OR user_id = 1 OR anon = true)  ORDER BY created_at desc LIMIT 10 OFFSET 0
```
saya cek di database sudah ada table relationships dan line yang berwarna merah adalah
```ruby
<% @articles.each do |item| %>
```
Terimakasih

**Comment by tsara27** [comment]
Have you run the migration? @MyHPPY

**Comment by MyHPPY** [comment]
yes, Iam run the command **rake db:create** and **rake db:migrate**

**Comment by MyHPPY** [comment]
please help @tsara27 @adeyahya

**Comment by tsara27** [comment]
@MyHPPY Is the table is existed in your database? Please make sure of it.

**Comment by MyHPPY** [comment]
Hi, yes the table is exists
![List table](http://w21.imgup.net/Screenshotb04d.png)

**Comment by MyHPPY** [comment]
Yes thanks for your support @tsara27  @adeyahya 
Iam edit model user

**Comment by adeyahya** [comment]
@MyHPPY There is something wrong in user model broh ? please tell me ..

**Comment by MyHPPY** [comment]
in models user.rb
before
```ruby
  def feed
    following_ids = "SELECT followed_id FROM Relationships WHERE follower_id = :user_id"
    Article.where("user_id IN (#{following_ids}) OR user_id = :user_id OR anon = true", user_id: id)
  end
```
after
```ruby
  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Article.where("user_id IN (#{following_ids}) OR user_id = :user_id OR anon = true", user_id: id)
  end
```

**Comment by adeyahya** [comment]
wow just it ? thanks @MyHPPY have you pull ? i made lot of change

**Comment by MyHPPY** [comment]
yes thanks for sharing @adeyahya
